#version 460 core

layout(local_size_x = 256,local_size_y = 1,local_size_z = 1) in;

struct Particle {
	vec3 position;
	vec3 velocity;
};

layout(std430, binding = 0) buffer ParticleBuffer
{
	Particle _Particles[]; // Buffer sent from the cpu to the gpu. Here vec3 and vec4 are equivalent
};

uniform int nBody; // Variable set by the cpu
uniform float deltaTime;
float gravityConstant = 0.00001;

float pi = 3.1459;

void main()
{
	uint index = gl_GlobalInvocationID.x;
	vec3 acceleration = vec3(0);
	vec3 position = _Particles[index].position;
	for(int j = 0; j < nBody; j++) {
		float r = distance(position,_Particles[j].position);
		r = max(0.001,r);
		acceleration += gravityConstant * (_Particles[j].position - position) / r;
	}
	_Particles[index].velocity += deltaTime * acceleration;
	_Particles[index].position += deltaTime * _Particles[index].velocity;
//	vec3 com = vec3(0);
//	for(int i = 0; i < nBody; i++) {
//		com += _Particles[i].position;
//	}
//	com/=nBody;
//	for(int i = 0; i < nBody; i++) {
//		_Particles[i].position -= com;
//	}
}