#pragma once
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include <stdio.h>
#include "GL/glew.h"
#include <GLFW/glfw3.h>
#include "shader.h"
#include "computeShader.h"
#include "screenQuad.h"
#include "renderer.h"
#include "postprocessing.h"
#include "texture.h"
#include "sphere.h"
#include "mathHelper.h"
#include "vec3.h"
#include "scene.h"