#version 460 core
#define M_PI 3.14159265358979

layout(std430, binding = 7) readonly restrict buffer TransfomBuffer
{
	vec3 _transforms[];
};

uniform int nBoids;

layout(local_size_x = 8,local_size_y = 8,local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D image;


void main()
{
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = vec2(pixelCoords)/imageSize(image);

	float dist = 1;
	vec3 pixelColor = vec3(0);
	for(int i = 0; i < nBoids; i++) {
		vec3 position = _transforms[i].xyz;
		vec2 screenPos = position.xy;
		float dist2 = dot(screenPos-uv,screenPos-uv);
		dist = min(dist,min(5000*dist2,1));	
	}
	pixelColor = vec3(dist*2);

	imageStore(image, pixelCoords, vec4(pixelColor,1));
}