#version 460 core
#define M_PI 3.14159265358979

struct Camera {
	vec3 position;
	vec3 direction;
	mat3x3 base;
	float vFov;
};

struct Ray {
	vec3 origin;
	vec3 direction;
};

Ray generateRay(ivec2 pixelCoords, ivec2 imSize, Camera camera) {
	vec2 screenPos = vec2(pixelCoords)/imSize * 2.0 - 1.0;

	float scale = tan(camera.vFov * M_PI / 360);
	float x = -screenPos.x * scale * float(imSize.x)/imSize.y;
	float y = screenPos.y * scale;

	Ray ray;
	ray.origin = camera.position;
	ray.direction = normalize(vec3(1, x, y));
	ray.direction = camera.base * ray.direction;

	return ray;
}

Ray generateRayOffset(ivec2 pixelCoords, ivec2 imSize, Camera camera, vec2 offset) {
	vec2 screenPos = vec2(pixelCoords + offset)/imSize * 2.0 - 1.0;

	float scale = tan(camera.vFov * M_PI / 360);
	float x = -screenPos.x * scale * float(imSize.x)/imSize.y;
	float y = screenPos.y * scale;

	Ray ray;
	ray.origin = camera.position;
	ray.direction = normalize(vec3(1, x, y));
	ray.direction = camera.base * ray.direction;

	return ray;
}