#version 460 core
#define M_PI 3.14159265358979

// STRUCTS
struct Transform {
	vec3 position;
	vec3 scale;
	vec2 rotation;
};

struct Ray {
	vec3 origin;
	vec3 direction;
};

uniform struct Camera {
	vec3 position;
	vec3 direction;
	mat3x3 base;
	float vFov;
} camera;

struct Light {
	vec3 direction;
	vec3 color;
	float radius;
} mainLight;

struct Hit {
	float depth;
	int index;
	int type;
};

struct Bounce {
	Ray ray;
	Hit hit;
	vec3 normal;
	vec3 color;
};

layout(std430, binding = 0) readonly restrict buffer TransfomBuffer
{
	Transform _transforms[];
};
layout(std430, binding = 1) readonly restrict buffer ColorBuffer
{
	vec3 _colors[];
};

layout(local_size_x = 16,local_size_y = 16,local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D image;

uniform int frameIndex;

int GIsamples = 4;

vec3 BRDF(vec3 lightColor, vec3 lightDirection, vec3 normal, vec3 color, float ambient) {
	return lightColor * M_PI * color * max(dot(normal,-lightDirection),0) + ambient * color;
}

vec3 skyColor(vec3 rayDirection);
Ray generateRay(ivec2 pixelCoords, ivec2 imSize, Camera camera);
Ray generateRayOffset(ivec2 pixelCoords, ivec2 imSize, Camera camera, vec2 offset);
Hit launchRay(Ray ray, int originIndex);
vec3 computeNormal(Hit hit, Ray ray);
float intersectSphere(Ray ray, Transform object);

vec3 BRDF(Light light, vec3 normal, vec3 color, float ambient) {
	return light.color * light.radius * light.radius * M_PI * color * max(dot(normal,-light.direction),0) + ambient * color;
}

uint getSeed(bool timeDependant) {
	if(timeDependant) return gl_GlobalInvocationID.x + 7491304 * gl_GlobalInvocationID.y + 435179 * frameIndex;
	else return gl_GlobalInvocationID.x + 74913 * gl_GlobalInvocationID.y;
}

float randFloat(uint seed, float a, float b) {
	uint state = seed*747796405u + 2891336453u;
	uint word = ((state >> ((state>>28u)+4u))^state)*277803737;
	word = (word>>22u)^word;
	return a+(b-a)*float(word)/(-1u);
}

vec3 biasedVector(vec3 axis, float theta, float phi) {
	vec3 orthVec = normalize(vec3(axis.z, axis.z, -(axis.x + axis.y)));

	vec3 u = axis * cos(theta) + orthVec * sin(theta);
	vec3 v = u * cos(phi) + cross(axis, u) * sin(phi) + axis * dot(axis, u) * (1 - cos(phi));
	return v;
}

Bounce computeAmbient(Ray lastRay, Hit lastHit, vec3 normal) {
	Bounce result;
	result.ray.origin = lastRay.origin + lastHit.depth * lastRay.direction;
	result.color = vec3(0);

	for(int i = 0; i < GIsamples; i++) {
		float u = randFloat(getSeed(true) + 1209492 * i + 137, 0, 1);
		float theta = .5 * acos(1 - 2 * u);
		float phi =	randFloat(getSeed(true) + 461721 * i, 0, 2 * M_PI);
		result.ray.direction = biasedVector(normal, theta, phi);

		result.hit = launchRay(result.ray, lastHit.index);
		if(result.hit.index != -1) {
			result.normal = computeNormal(result.hit, result.ray);
			vec3 hitColor = BRDF(mainLight, result.normal, _colors[result.hit.index], 0.01) * _colors[lastHit.index];
			result.color += hitColor * M_PI / 4;
		}
	}

	return result;
}
uniform struct Count {
	int sphere;
	int cube;
	int plane;
	int circle;
	int cylinder;
	int cone;
	int pyramid;
} count;
void main()
{
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

	Ray ray = generateRay(pixelCoords, imageSize(image), camera);

	mainLight.radius = .1;
	mainLight.direction = vec3(1,0,0);
	mainLight.color = vec3(30.);

	vec3 skyColor = pow(.4 * skyColor(ray.direction), vec3(1.,1.,.9));
	if(dot(ray.direction,-mainLight.direction)>cos(mainLight.radius)) {
		skyColor = mainLight.color;
	}
	Hit firstHit = launchRay(ray, -1);
	vec3 pixelColor = skyColor;
	if(firstHit.index!=-1) {
		vec3 normal =  computeNormal(firstHit, ray);
		pixelColor = BRDF(mainLight, normal, vec3(_colors[firstHit.index]), 0.0);
		if(GIsamples > 0) {
			Bounce bounce1 = computeAmbient(ray, firstHit, normal);
			pixelColor += bounce1.color / GIsamples;
			//Bounce bounce2 = computeAmbient(bounce1.ray, bounce1.hit, bounce1.normal);
			//pixelColor += bounce2.color / GIsamples;
		}
	}

	imageStore(image, pixelCoords, vec4(pixelColor,1));
}